// Generated by LiveScript 1.2.0
(function(){
  var SpriteStroker, x$, ref$;
  SpriteStroker = (function(){
    SpriteStroker.displayName = 'SpriteStroker';
    var prototype = SpriteStroker.prototype, constructor = SpriteStroker;
    SpriteStroker.loaders = {
      xml: zhStrokeData.loaders.XML,
      json: zhStrokeData.loaders.JSON,
      bin: zhStrokeData.loaders.Binary
    };
    function SpriteStroker(str, options){
      var res$, i$, ref$, len$, ch, p;
      this.options = $.extend({
        autoplay: false,
        width: 0,
        height: 0,
        loop: false,
        preload: 4,
        poster: '',
        url: './json/',
        dataType: 'json',
        speed: 150,
        strokeDelay: 0.1,
        charDelay: 0.2
      }, options);
      this.loop = this.options.loop;
      this.preload = this.options.preload;
      this.width = this.options.width;
      this.height = this.options.height;
      this.posters = this.options.posters;
      this.url = this.options.url;
      this.dataType = this.options.dataType;
      this.speed = this.options.speed;
      this.strokeDelay = this.options.strokeDelay;
      this.charDelay = this.options.charDelay;
      res$ = [];
      for (i$ = 0, len$ = (ref$ = str.sortSurrogates()).length; i$ < len$; ++i$) {
        ch = ref$[i$];
        res$.push(constructor.loaders[this.dataType](this.url + "" + ch.codePointAt().toString(16) + "." + this.dataType));
      }
      this.promises = res$;
      for (i$ = 0, len$ = (ref$ = this.promises).length; i$ < len$; ++i$) {
        p = ref$[i$];
        p.then(fn$);
      }
      function fn$(it){
        return console.log(it);
      }
    }
    prototype.videoTracks = 1;
    prototype.autoplay = false;
    prototype.buffered = null;
    prototype.currentTime = 0;
    prototype.defaultPlaybackRate = 1.0;
    prototype.PlaybackRate = 1.0;
    prototype.duration = 0;
    prototype.ended = false;
    prototype.error = null;
    prototype.loop = false;
    prototype.paused = false;
    prototype.played = false;
    prototype.preload = 4;
    prototype.seekable = null;
    prototype.seeking = false;
    prototype.canPlayType = function(str){
      return 'probably' || 'maybe' || '';
    };
    prototype.fastSeek = function(time){};
    prototype.load = function(){};
    prototype.pause = function(){};
    prototype.play = function(){};
    prototype.width = 0;
    prototype.height = 0;
    prototype.videoWidth = 0;
    prototype.videoHeight = 0;
    prototype.poster = 0;
    return SpriteStroker;
  }());
  x$ = (ref$ = window.zhStrokeData) != null
    ? ref$
    : window.zhStrokeData = {};
  x$.SpriteStroker = SpriteStroker;
}).call(this);
