// Generated by LiveScript 1.2.0
(function(){
  var SpriteStroker, ref$, ref1$;
  SpriteStroker = (function(){
    SpriteStroker.displayName = 'SpriteStroker';
    var prototype = SpriteStroker.prototype, constructor = SpriteStroker;
    function SpriteStroker(options){
      this.options = $.extend({
        autoplay: false,
        controls: false,
        width: 0,
        height: 0,
        loop: false,
        muted: true,
        preload: 'metadata',
        poster: '',
        src: ''
      });
    }
    prototype.audioTracks = 0;
    prototype.videoTracks = 0;
    prototype.textTracks = 0;
    prototype.autoplay = false;
    prototype.buffered = null;
    prototype.controller = null;
    prototype.controls = SpriteStroker.options.consoles;
    prototype.currentSrc = SpriteStroker.src;
    prototype.src = SpriteStroker.options.src;
    prototype.currentTime = 0;
    prototype.defaultMuted = SpriteStroker.options.muted;
    prototype.muted = SpriteStroker.defaultMuted;
    prototype.defaultPlaybackRate = 1.0;
    prototype.PlaybackRate = SpriteStroker.defaultPlaybackRate;
    prototype.duration = 0;
    prototype.ended = false;
    prototype.error = null;
    prototype.initialTime = 0;
    prototype.loop = SpriteStroker.options.loop;
    prototype.mediaGroup = '';
    prototype.paused = false;
    prototype.played = false;
    prototype.preload = SpriteStroker.options.preload;
    prototype.seekable = null;
    prototype.seeking = false;
    prototype.volume = 0;
    prototype.canPlayType = function(str){
      return 'probably' || 'maybe' || '';
    };
    prototype.fastSeek = function(time){};
    prototype.load = function(){};
    prototype.pause = function(){};
    prototype.play = function(){};
    prototype.width = SpriteStroker.options.width;
    prototype.height = SpriteStroker.options.height;
    prototype.videoWidth = 0;
    prototype.videoHeight = 0;
    prototype.poster = SpriteStroker.options.poster;
    return SpriteStroker;
  }());
  (ref$ = (ref1$ = window.zhStrokeData) != null
    ? ref1$
    : window.zhStrokeData = {}).stroker == null && (ref$.stroker = {});
  window.zhStrokeData.SpriteStroker = SpriteStroker;
}).call(this);
