// Generated by LiveScript 1.2.0
(function(){
  $(function(){
    return $.get('../../orig-chars.json', function(OrigChars){
      var shiftFloat, shapesFromOutline;
      console.log(OrigChars);
      shiftFloat = function(){
        return parseFloat(this.shift());
      };
      return shapesFromOutline = function(it){
        var i$, len$, stroke, shape, path, current, tokens, results$ = [];
        for (i$ = 0, len$ = it.length; i$ < len$; ++i$) {
          stroke = it[i$];
          shape = new THREE.Shape;
          path = new THREE.Path;
          current = shape;
          tokens = stroke.split(' ');
          while (tokens.length) {
            switch (tokens.shift()) {
            case 'M':
              current.moveTo(shiftFloat.call(tokens), shiftFloat.call(tokens));
              break;
            case 'L':
              while (tokens.length > 1) {
                current.lineTo(shiftFloat.call(tokens), shiftFloat.call(tokens));
                if (tokens[0] === 'Z') {
                  if (current !== shape) {
                    shape.holes.push(path);
                    path = new THREE.Path;
                  }
                  current = path;
                  break;
                }
              }
            }
          }
          results$.push(shape);
        }
        return results$;
      };
    });
  });
}).call(this);
