// Generated by LiveScript 1.2.0
$(function(){
  var ss, $sdelay, $cdelay, update, ps;
  ss = new zhStrokeData.SpriteStroker('宅度不同', {
    url: '../../json/'
  });
  $sdelay = $('#sdelay');
  $cdelay = $('#cdelay');
  $('#sprite').append(ss.domElement);
  $('#speed').change(function(){
    ss.speed = +$(this).val();
  }).val(ss.speed);
  $('#stroke').change(function(){
    ss.strokeDelay = +$(this).val();
    $sdelay.text(ss.strokeDelay);
  }).val(ss.strokeDelay);
  $sdelay.text(ss.strokeDelay);
  $('#char').change(function(){
    ss.charDelay = +$(this).val();
    $cdelay.text(ss.charDelay);
  }).val(ss.charDelay);
  $cdelay.text(ss.charDelay);
  $('#play').click(function(){
    ss.pause(false);
    ss.play();
  });
  $('#pause').click(function(){
    ss.pause(true);
  });
  update = function(){
    $('#progress').val(ss.currentTime);
    requestAnimationFrame(update);
  };
  requestAnimationFrame(update);
  ps = new zhStrokeData.PrintingStroker('兩天當一天', {
    url: '../../json/'
  });
  return $('#printing').append(ps.domElement);
});