// Generated by LiveScript 1.2.0
$(function(){
  var ss;
  ss = new zhStrokeData.SpriteStroker('你那邊幾點', {
    url: '../../json/'
  });
  $('body').append(ss.domElement);
  $('#speed').change(function(){
    ss.speed = +$(this).val();
  }).val(ss.speed);
  $('#stroke').change(function(){
    ss.strokeDelay = +$(this).val();
  }).val(ss.strokeDelay);
  $('#char').change(function(){
    ss.charDelay = +$(this).val();
  }).val(ss.charDelay);
  $('#play').click(function(){
    ss.pause(false);
    ss.play();
  });
  return $('#pause').click(function(){
    ss.pause(true);
  });
});