// Generated by LiveScript 1.2.0
$(function(){
  var x$, canvas, y$, colors, p;
  x$ = canvas = document.createElement('canvas');
  x$.width = 2150;
  x$.height = 2150;
  y$ = x$.style;
  y$.width = '430px';
  y$.height = '430px';
  $('#sprite').append(canvas);
  colors = ['#1abc9c', '#2ecc71', '#3498db', '#9b59b6', '#34495e'];
  p = zhStrokeData.loaders.JSON("../../json/" + '品'.codePointAt().toString(16) + ".json");
  return p.then(function(it){
    var ss, res$, i$, len$, data, boxes, s, ctx, i, ref$, g, b;
    res$ = [];
    for (i$ = 0, len$ = it.length; i$ < len$; ++i$) {
      data = it[i$];
      res$.push(new zhStrokeData.Stroke(data));
    }
    ss = res$;
    res$ = [];
    for (i$ = 0, len$ = ss.length; i$ < len$; ++i$) {
      s = ss[i$];
      res$.push(s.aabb);
    }
    boxes = res$;
    ctx = canvas.getContext('2d');
    for (i in ref$ = zhStrokeData.AABB.rdc(boxes)) {
      g = ref$[i];
      for (i$ = 0, len$ = g.length; i$ < len$; ++i$) {
        b = g[i$];
        b.render(ctx, colors[i]);
      }
    }
    return console.log(zhStrokeData.AABB.hit(boxes));
  });
});